### ISSUE TITLE
Game Graph & Strikezone Map Links use UTC for Date Parameter

### ISSUE THREAD

**Issue by immoderate** [Fustrate/baseballbot.io#6]
There is an issue in the `Game Graph` and `Strikezone Map` links. 

The date parameter in the URL is a date value based on UTC time, so a 7PM CDT start time will pass tomorrow's date and that results in an error when visiting the link.

You can see what I am talking about if you look at today's game thread [here](https://old.reddit.com/r/Astros/comments/nc81h0/game_thread_rangers_1821_astros_2117_may_14_2021/), the links are: 

http://www.fangraphs.com/livewins.aspx?date=2021-05-15&team=Astros&dh=0&season=2021
http://www.brooksbaseball.net/pfxVB/zoneTrack.php?month=05&day=15&year=2021&game=gid_2021_05_14_texmlb_houmlb_1%2F

The correct links are:

http://www.fangraphs.com/livewins.aspx?date=2021-05-14&team=Astros&dh=0&season=2021
http://www.brooksbaseball.net/pfxVB/zoneTrack.php?month=05&day=14&year=2021&game=gid_2021_05_14_texmlb_houmlb_1%2F

At game time the correct link will yield the expected content, but the bad link will return the error page.

**Comment by Fustrate** [comment]
I've fixed the links in https://github.com/Fustrate/baseballbot/commit/1124c19d186bc703e4f2b53deb3f59889fc73867 but I think Brooks Baseball has shut down the strike zone map feature and moved to a pitcher-by-pitcher system. Even the correct link returns an Access Denied page, and I can't find the feature on their website anymore. I'm going to remove that link from the templates going forward - I don't think it was used often enough to replace since the pages on their site are only available after the end of the game.
